ADD annotation
multiomics/multiomics-configs pull request #102
Opened 2022-05-28 01:57 UTC by tangpeikun

2022-05-28 06:53 UTC, ypriverol requested changes

2022-05-28 06:53 UTC, ypriverol commented on datasets/differential-datasets/dia/PXD010690/PXD010690.sdrf.tsv
> +PXD010690-Sample 1	Homo sapiens	Brain	not available	not available	not applicable	not available	not available	not available	1	whole organism	run 17	proteomic profiling by mass spectrometry	NT=Data-Ind
PXD010690-Sample-1. Please for each sample add the - before the number

2022-06-01 00:19 UTC, merged

2022-06-01 00:19 UTC, hardworkinghhq commented on datasets/differential-datasets/dia/PXD010690/PXD010690.sdrf.tsv
> +PXD010690-Sample 1	Homo sapiens	Brain	not available	not available	not applicable	not available	not available	not available	1	whole organism	run 17	proteomic profiling by mass spectrometry	NT=Data-Ind
1

2022-06-01 00:19 UTC, hardworkinghhq commented
1