4 new datasets added
multiomics/multiomics-configs pull request #176
Opened 2023-04-06 15:07 UTC by asierlarrea

2023-04-06 15:30 UTC, asierlarrea commented
PXD006559: columns 19 (comment[fractionation method]) maybe "in-house constructed IPG extractor robotics"
PXD006559: columns 20 (comment[label]) don't know TMT ontology
PXD006559: columns 29 (comment[collision energy]) maybe "30% normalized collision energy"
PXD006559: columns 30 (comment[precursor mass tolerance]) maybe "Precursors were isolated with a 2 m/z"

2023-04-07 07:11 UTC, daichengxin commented
> PXD006559: columns 19 (comment[fractionation method]) maybe "in-house constructed IPG extractor robotics" PXD006559: columns 20 (comment[label]) don't know TMT ontology PXD006559: columns 29 (comment[collision energy]) maybe "30% normalized collision energy" PXD006559: columns 30 (comment[precursor mass tolerance]) maybe "Precursors were isolated with a 2 m/z"

`comment[fractionation method]` is an optional column, it can be removed. 
`comment[label]` should specify specific  channel for TMT, such as TMT126, TMT127N.  
`collision energy` 30% NCE 
`comment[precursor mass tolerance]` should be found in `Peptide and protein identification and quantification` section in the paper. `A precursor ion mass tolerance of 10 ppm, and product ion mass tolerances of 0.02 Da`

2023-04-07 07:25 UTC, daichengxin commented
> PXD038674: columns 5 (characteristics[cell type]) don't know ontology for "Platelet-derived extracellular vesicle"

In PXD038674, The sample should be same for technical replicates. The precursor and fragment tolerence can be 4.5ppm and 20ppm, respectivly. The optional column can be removed or put "not available" in here when you don't know the context, such as collision energy.

2023-04-07 07:33 UTC, daichengxin commented on projects/plasma-proteomes/PXD006559/PXD006559.sdrf.tsv
> +PXD006559-Sample-1	Homo sapiens	blood plasma		platelet	not available	not available	male	not available	healthy	no depletion	1	not applicable	Mattias_JPGNAW2-11_20150521_QEN_TMT10_350ugIPG3-10_7of15ul_
Put `not available` in `characteristics[individual]` column. The `comment[MS2 mass analyzer]` and `comment[separation]` could be removed, because they are optional. Then add tolerence

2023-04-16 13:15 UTC, ypriverol commented
@daichengxin can you have a look to this?

2023-04-17 12:52 UTC, daichengxin requested changes

2023-04-17 12:52 UTC, daichengxin commented on projects/plasma-proteomes/PXD020727/PXD020727.sdrf.tsv
Could you fill the instrument column?  Wrong modification name: `Carbamylation`

2023-04-17 12:52 UTC, daichengxin commented on projects/plasma-proteomes/PXD006559/PXD006559.sdrf.tsv
The label column should specify a channel such as TMT126, and then you must duplicate file column.  You can see the example :https://github.com/multiomics/multiomics-configs/blob/master/datasets/differential-datasets/tmt/PXD002875/PXD002875.sdrf.tsv. When you annotating, you can find useful informations in supplementary files and else.

2023-04-17 12:52 UTC, daichengxin commented on projects/plasma-proteomes/PXD002854/Serum.sdrf.tsv
The same fraction group must have same source names. For example, 1-48 fraction identifier should be same samples.

2023-04-17 15:06 UTC, asierlarrea commented on projects/plasma-proteomes/PXD004352/PXD004352.sdrf.tsv
> +PXD004352-Sample-1	Homo sapiens	Blood	1	Regulatory T cell	not available	not available	not available	not available	Healthy	no depletion	1	not available	20131115_EXQ2_JaRi_SA_Do132_Memory_Free_Act_01	p
I have already modified the parameter, but what is a "TA"? Where can I find it? I have been copying the TA for the other modifications, but Deamidated is new for my and I don't know how to look for tha information

2023-04-17 15:09 UTC, asierlarrea commented on projects/plasma-proteomes/PXD038674/PXD038674.sdrf.tsv
As far as I know, there are only healthy and colorectal cancer (CRC) patients. I haven't found any ontology for CRC, so I have write that in the disease column. I am missing something?

2023-04-17 15:11 UTC, asierlarrea commented on projects/plasma-proteomes/PXD020727/PXD020727.sdrf.tsv
Why is Carbamylation wrong? I found this in the article: carbamidomethylation at
cysteine, while methionine oxidation, N-terminal carbamylation and N-terminal acetylation were set
as dynamic

2023-04-19 04:51 UTC, ypriverol commented on projects/plasma-proteomes/PXD038674/PXD038674.sdrf.tsv
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005842

2023-04-19 04:56 UTC, merged